config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins

  # ユーザ用ルーティング
  devise_for :users

  resources :users, only: %i[show edit update] do
    get 'users/following', to: 'users#following', on: :member
    get 'users/follower', to: 'users#follower', on: :member
    get 'likes', to: 'likes#index', on: :member
  end
  get 'users/:id/exit' => 'users#exit', as: 'exit'
  get 'users/:id/follower' => 'users#follower', as: 'follower'
  get 'users/:id/following' => 'users#following', as: 'following'

  resources :post_gardens, only: %i[new create show edit update destroy] do
    resources :post_comments, only: %i[create destroy]
    post 'likes', to: 'likes#create', on: :member
    delete 'likes', to: 'likes#destroy', on: :member
    post 'send_images', to: 'post_gardens#send_images', on: :collection
  end
  root to: 'post_gardens#index'
  get 'about' => 'post_gardens#about', as: 'about'
  get 'post_gardens/:id/new_open_garden' => 'post_gardens#new_open_garden', as: 'new_open_garden'
  get 'search_result' => 'post_gardens#search_result', as: 'search_result'
  patch 'post_gardens/:id/delete_open_info' => 'post_gardens#delete_open_info', as: 'delete_open_info'

  resources :post_images, only: [:destroy]

  resources :open_days, only: %i[create update destroy]
  # resources :new_open_garden

  resources :relationships, only: [:create]
  delete 'relationships/:id' => 'relationships#destroy', as: 'unfollow'

  resources :reservations, only: %i[create show edit update]
  get 'reservations/new/:id' => 'reservations#new', as: 'new_reservation'
  get 'done' => 'reservations#done', as: 'done'
  get 'accept_reservations/:id' => 'reservations#accept_reservations', as: 'accept_reservations'
  get 'request_reservations/:id' => 'reservations#request_reservations', as: 'request_reservations'
  get 'approve_reservation/:id' => 'reservations#approve_reservation', as: 'approve_reservation'
  get 'approved/:id' => 'reservations#approved', as: 'approved'
  get 'cancel_reason/:id' => 'reservations#cancel_reason', as: 'cancel_reason'
  get 'canceled/:id' => 'reservations#canceled', as: 'canceled'

  resources :notifications, only: :index

  resources :search_plants, only: %i[new show create]
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # 県の選択肢一覧
  enum prefecture: { "北海道": 0, "青森県": 1, "岩手県": 2, "宮城県": 3, "秋田県": 4, "山形県": 5, "福島県": 6, "茨城県": 7, "栃木県": 8, "群馬県": 9, "埼玉県": 10, "千葉県": 11, "東京都": 12, "神奈川県": 13, "新潟県": 14, "富山県": 15, "石川県": 16, "福井県": 17, "山梨県": 18, "長野県": 19, "岐阜県": 20, "静岡県": 21, "愛知県": 22, "三重県": 23, "滋賀県": 24, "京都府": 25, "大阪府": 26, "兵庫県": 27, "奈良県": 28, "和歌山県": 29, "鳥取県": 30, "島根県": 31, "岡山県": 32, "広島県": 33, "山口県": 34, "徳島県": 35, "香川県": 36, "愛媛県": 37, "高知県": 38, "福岡県": 39, "佐賀県": 40, "長崎県": 41, "熊本県": 42, "大分県": 43, "宮崎県": 44, "鹿児島県": 45, "沖縄県": 46 }

  # ユーザモデルのバリデーション
  validates :user_name, presence: true, length: { maximum: 15 }
  validates :postal_code, presence: true, length: { is: 7 }
  validates :prefecture, presence: true
  validates :address, presence: true, length: { maximum: 70 }
  validates :phone_number, presence: true, length: { maximum: 15 }
  validates :email, presence: true
  validates :profile_text, length: { maximum: 100 }

  attachment :profile_image

  has_many :post_gardens, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :reservations

  # フォロー機能のアソシエーション
  has_many :relationships
  # followingsと命名（followingモデルを架空に作成）follow_idを参考にfollowingモデルにアクセスさせる
  has_many :followings, through: :relationships, source: :follow
  # reverse_of_relationshipsを命名（class_nameでrelationshipモデルのことを表す）
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  # followersと命名（followerモデルを架空に作成）user_idを参考にfollowersモデルにアクセスさせる
  has_many :followers, through: :reverse_of_relationships, source: :user

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # 通知機能用リレーション
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  # フォロー機能のメソッド
  def follow(other_user)
    unless self == other_user
      relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = relationships.find_by(follow_id: other_user.id)
    relationship&.destroy
  end

  def following?(other_user)
    followings.include?(other_user)
  end

  # フォロー一覧を表示させる際の、フォローかフォロー解除かの判定
  # userではなくidを引数にしているため、どのユーザかfind_byしている
  def user_following?(other_user)
    user = followings.find_by(id: other_user)
    followings.include?(user)
  end

  def user_followed?(other_user)
    user = followers.find_by(id: other_user)
    followers.include?(user)
  end

  # 通知機能のメソッド
  def create_notification_follow!(current_user)
    temp = Notification.where(['visitor_id = ? and visited_id = ? and action = ? ', current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @post_gardens = PostGarden.where(user_id: @user.id).includes([:post_images]).includes([:user]).includes([:taggings])
    @relationship = Relationship.new

    @relationship_followers = Relationship.where(follow_id: @user.id)
    @relationship_followings = Relationship.where(user_id: @user.id)

    # カレンダーに登録するイベント
    if user_signed_in?
      @visit_requests = Reservation.where(user_id: current_user.id).where(request_status: '承認')
      @accept_requests = Reservation.where(owner_id: current_user.id).where(request_status: '承認')
    end
  end

  def edit
    @user = User.find(params[:id])

    @visit_requests = Reservation.where(user_id: current_user.id).where(request_status: '承認')
    @accept_requests = Reservation.where(owner_id: current_user.id).where(request_status: '承認')
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render 'edit'
    end
  end

  def exit
    @user = User.find(params[:id])
  end

  def follower
    @user = User.find(params[:id])
    @followers = Relationship.where(follow_id: params[:id]).includes([:user])
    @relationship = Relationship.new
  end

  def following
    @user = User.find(params[:id])
    @followings = Relationship.where(user_id: params[:id]).includes([:follow])
    @relationship = Relationship.new
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :postal_code, :prefecture, :address, :phone_number, :email, :profile_image, :profile_text)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
	<div class="row">
		<h2>会員情報編集</h2>

		<%= form_for (@user), url: user_path do |f| %>

			<div class="col-xs-6 col-xs-offset-3">
		      <%= f.label :ユーザ名, class: "float-left" %><br />
		      <%= f.text_field :user_name, autofocus: true, autocomplete: "user_name", class:"col-auto form-control form-control-lg w-100" %>
		    </div>

		    <div class="col-xs-6 col-xs-offset-3">
		    	<%= attachment_image_tag @user, :profile_image, :fill, 50, 50, format: 'jpg', fallback: "no_image.jpg" %>
		        <%= f.attachment_field :profile_image %>
		    </div>

		    <div class="col-xs-6 col-xs-offset-3">
		      <%= f.label :郵便番号（ハイフンを除いた７桁の数字） %><br />
		      <%= f.text_field :postal_code, class:"col-auto form-control form-control-lg w-100" %>
		    </div>

		    <div class="col-xs-6 col-xs-offset-3">
		      <%= f.label :都道府県 %><br />
		      <%= f.select :prefecture, User.prefectures.keys.to_a, class:"col-auto form-control form-control-lg w-100" %>
		    </div>

		    <div class="col-xs-6 col-xs-offset-3">
		      <%= f.label :住所 %><br />
		      <%= f.text_field :address, class:"col-auto form-control form-control-lg w-100" %>
		    </div>

		    <div class="col-xs-6 col-xs-offset-3">
		      <%= f.label :電話番号 %><br />
		      <%= f.text_field :phone_number, class:"col-auto form-control form-control-lg w-100" %>
		    </div>

		    <div class="col-xs-6 col-xs-offset-3">
		      <%= f.label :メールアドレス %><br />
		      <%= f.email_field :email, autocomplete: "email", class:"col-auto form-control form-control-lg w-100" %>
		    </div>

		    <div class="col-xs-6 col-xs-offset-3">
		      <%= f.label :フロフィール文 %><br />
		      <%= f.text_area :profile_text, class:"col-auto form-control form-control-lg w-100" %>
		    </div>


			<div class="actions">
				<%= f.submit "更新", class:"col-xs-4 col-xs-offset-4 btn btn-primary" %>
			</div>

		<% end %>


		<%= link_to "退会する", exit_path(@user.id) %>


	</div>
</div>

app/views/users/exit.html.erb
<div class="container">
	<div class="row">

		<div class="col-xs-6 col-xs-offset-3">

			<div class="exit-title">
				<h3 class="exit-title-text">退会する</h3>
			</div>

			<h5 class="exit-message">下記の登録情報が消え、すべてご利用できなくなります。</h5>
  	  		<ul class="exit-list">
		  	    <li>会員情報</li>
		  	    <li>お気に入り</li>
		  	    <li>庭の投稿</li>
		  	    <li>庭の予約</li>
  			</ul>


  			<div class="exit-confirm">
  				<%= link_to '退会する', user_registration_path, method: :delete, class: "btn btn-danger", "data-confirm" => "Gardeniaを退会します。よろしいですか？" %>
  			</div>

  		</div>
	</div>
</div>

app/views/users/follower.html.erb
<div class="container">
	<div class="row">

		<div class="col-xs-4 col-xs-offset-1">
			<div class="follower-index-title-position">
				<%= attachment_image_tag @user, :profile_image, :fill, 50, 50, format: 'jpg', fallback: "no_image.jpg", class:"index-profile-image" %>
				<span class="follower-index-title-text"><strong><%= @user.user_name %>のフォロワー</strong></span>
			</div>
		</div>

	</div>

	<!-- フォロワー一覧 -->
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1">
			<% @followers.each do |follower| %>


				<div class="row follower-index-list">
					<div class="col-xs-3 col-xs-offset-1">
						<%= attachment_image_tag follower.user, :profile_image, :fill, 50, 50, format: 'jpg', fallback: "no_image.jpg", class:"index-profile-image" %>
						<%= link_to user_path(follower.user_id), class:"follower-index-user-name" do %>
							<strong><%= follower.user.user_name %></strong>
						<% end %>
					</div>

					<div class="col-xs-3 follow-index-profile-content">
						<%= follower.user.profile_text %>
					</div>


					<div class="col-xs-1 col-xs-offset-1 follow-index-prefecture">
						<span class="follow-index-prefecture-text"><%= follower.user.prefecture %></span>
					</div>

					<div class="col-xs-2">
						<% if user_signed_in? %>
							<% if current_user.id != follower.user_id %>
								<% if current_user.user_followed?(follower.user_id) %>
									<%= form_for(current_user.relationships.find_by(follow_id: follower.user_id), url: unfollow_path(follower.user_id), html: { method: :delete }) do |f| %>
										<%= hidden_field_tag :follow_id, follower.id %>
										<%= f.submit 'フォロー解除', class:"btn btn-danger btn-sm follower-index-button-position" %>
									<% end %>
								<% else %>
									<%= form_for(@relationship) do |f| %>
										<%= hidden_field_tag :follow_id, follower.id %>
										<%= f.submit '+ フォロー', class:"btn btn-primary btn-sm follower-index-button-position" %>
									<% end %>
								<% end %>
							<% end %>
						<% end %>
					</div>
				</div>

			<% end %>
		</div>
	</div>
</div>

app/views/users/following.html.erb
<div class="container">
	<div class="row">

		<div class="col-xs-4 col-xs-offset-1">
			<div class="follower-index-title-position">
				<%= attachment_image_tag @user, :profile_image, :fill, 50, 50, format: 'jpg', fallback: "no_image.jpg", class:"index-profile-image" %>
				<span class="follower-index-title-text"><strong><%= @user.user_name %>がフォロー中</strong></span>
			</div>
		</div>

	</div>

	<!-- フォロワー一覧 -->
	<div class="row">
		<div class="col-xs-11 col-xs-offset-1">
			<% @followings.each do |following| %>

				<div class="row follower-index-list">
					<div class="col-xs-3 col-xs-offset-1">
						<%= attachment_image_tag following.follow, :profile_image, :fill, 50, 50, format: 'jpg', fallback: "no_image.jpg", class:"index-profile-image" %>
						<%= link_to user_path(following.follow_id), class:"follower-index-user-name" do %>
							<strong><%= following.follow.user_name %></strong>
						<% end %>
					</div>

					<div class="col-xs-3 follow-index-profile-content">
						<%= following.follow.profile_text %>
					</div>


					<div class="col-xs-1 col-xs-offset-1 follow-index-prefecture">
						<span class="follow-index-prefecture-text"><%= following.follow.prefecture %></span>
					</div>

					<div class="col-xs-2">
						<% if user_signed_in? %>
							<% if current_user.id != following.follow_id %>
								<% if current_user.user_following?(following.follow_id) %>
									<%= form_for(current_user.relationships.find_by(follow_id: following.follow_id), url: unfollow_path(following.follow_id), html: { method: :delete }) do |f| %>
										<%= hidden_field_tag :follow_id, following.id %>
										<%= f.submit 'フォロー解除', class:"btn btn-danger btn-sm follower-index-button-position" %>
									<% end %>
								<% else %>
									<%= form_for(@relationship) do |f| %>
										<%= hidden_field_tag :follow_id, following.id %>
										<%= f.submit '+ フォロー', class:"btn btn-primary btn-sm follower-index-button-position" %>
									<% end %>
								<% end %>
							<% end %>
						<% end %>
					</div>
				</div>

			<% end %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		
		<div class="col-xs-2">
			<div class="mp-samuneiru-position">
			<%= attachment_image_tag @user, :profile_image, :fill, 150, 150, format: 'jpg', fallback: "no_image.jpg", class:"index-profile-image" %>
			</div>

		</div>

		<div class="col-xs-5">

			<div class="mp-info">

				<!-- 他のユーザのページだったら、フォローボタンを設置 -->
				<% if user_signed_in? %>
					<% unless current_user == @user %>
						<% if current_user.following?(@user) %>
							<%= form_for(current_user.relationships.find_by(follow_id: @user.id), url: unfollow_path(@user.id), html: { method: :delete }) do |f| %>
								<%= hidden_field_tag :follow_id, @user.id %>
								<%= f.submit 'フォロー解除', class:"btn btn-danger follow-button-position" %>
							<% end %>
						<% else %>
							<%= form_for(@relationship) do |f| %>
								<%= hidden_field_tag :follow_id, @user.id %>
								<%= f.submit '+ フォロー', class:"btn btn-primary follow-button-position" %>
							<% end %>
						<% end %>
					<% end %>
				<% end %>


				<span class="mp-user-info">
					<strong><%= @user.user_name %></strong>
				</span>

				<!-- 自ユーザならば、投稿の編集 -->
				<% if user_signed_in? %>
					<% if @user.id == current_user.id %>
						<span class="mp-edit-user">
							<%= link_to "会員情報編集", edit_user_path(@user.id), class:"btn btn-primary btn-sm" %>
						</span>
					<% end %>
				<% end %>


				<div class="follow-index">
					<span class="post-num">投稿<%= @user.post_gardens.count %>件</span>

					<span class="follower-text">
						<%= link_to follower_path(params[:id]), class:"follow-link" do %>
							フォロワー<%= @relationship_followers.count %>人
						<% end %>
					</span>

					<span class="following-text">
						<%= link_to following_path(params[:id]), class:"follow-link" do %>
							<%= @relationship_followings.count %>人をフォロー中
						<% end %>
					</span>
				</div>

				<div class="mp-place-box">
					<span class="mp-place-text"><%= @user.prefecture %></span>
				</div>

				<div class="mp-profile-content">
					<span class="mp-profile-content-text"><%= @user.profile_text %></span>
				</div>


				<div class="like-reservation-index">
					<div class="row">
						<div class="col-xs-4">
							<span class="like-index"><%= link_to "いいねした庭園", likes_user_path(@user.id), class:"btn btn-default" %></span>
						</div>

						<% if user_signed_in? %>
							<% if current_user == @user %>
								<div class="col-xs-4">
									<span class="reservation-request-index"><%= link_to "予約済の庭園一覧", request_reservations_path, class:"btn btn-default" %></span>
								</div>

								<div class="col-xs-4">
									<span class="reservation-accept-index"><%= link_to "庭園の見学予約", accept_reservations_path, class:"btn btn-default" %></span>
								</div>
							<% end %>
						<% end %>
					</div>
				</div>

			</div>

		</div>


		<!-- スケジュール管理 -->
		<% if user_signed_in? %>
			<% if current_user == @user %>
				<div class="col-xs-4 reserve-calendar-border">

					<div class="reservation-new-event">
						<span class="reservation-new-event-text"><strong><i class="far fa-calendar-alt"></i>予約カレンダー</strong></span>
					</div>
					<div id="calendar-user"></div>

					<div class="request-example-color">
						<span class="request-color"></span>
						<span class="request-color-text"> ••• 訪問が確定している予約</span>
					</div>

					<div class="accept-example-color">
						<span class="accept-color"></span>
						<span class="accept-color-text"> ••• 他ユーザの来訪が確定している予約</span>
					</div>
					<!-- どの投稿のカレンダーか判別するため、idをjqueryに渡している -->
					<div class="params_num_user" data-params="<%= @user.id %>"></div>
				</div>
			<% else %>

				<div class="col-xs-4 reserve-calendar-border">

					<div class="reservation-new-event">
						<span class="reservation-new-event-text"><strong><i class="far fa-calendar-alt"></i>予約カレンダー</strong></span>
					</div>

					<div class="not-yet-my-mp">
						<span>他のユーザの予定は見ることができません</span>
					</div>

				</div>

			<% end %>
		<% else %>
			<div class="col-xs-4 reserve-calendar-border">

				<div class="reservation-new-event">
					<span class="reservation-new-event-text"><strong><i class="far fa-calendar-alt"></i>予約カレンダー</strong></span>
				</div>

				<div class="not-yet-my-mp">
					<span>他のユーザの予定は見ることができません</span>
				</div>

			</div>
		<% end %>
	</div>

	<!-- 投稿一覧 -->
	<div class="row">
		<div class="col-xs-10">

			<div class="mp-post-index">
				<span class="mp-post-index-text"><strong><i class="fas fa-pen"></i>投稿一覧</strong></span>
			</div>

			<div class="user-post-index">
				<% @post_gardens.each do |post_garden| %>

					<!-- cssはトップページ(post_garden indexと同じ) -->
					<div class="col-xs-3">
						<%= link_to post_garden_path(post_garden.id) do %>
							<%= attachment_image_tag post_garden.post_images[0], :garden_image, :fill, 200,200, format: 'jpg', class:"index-post-image" %>
						<% end %>

						<div class="post-index">
							<div class="index-profile-image-position">
								<%= link_to user_path(post_garden.user.id), class:"profile-image-link" do %>
									<%= attachment_image_tag post_garden.user, :profile_image, :fill, 30,30, format: 'jpg', class:"index-profile-image" %>
									<span class="profile-image-name"><%= post_garden.user.user_name %></span>
								<% end %>
							</div>

							<div class="tags-list-index">
								<% post_garden.tag_list.each do |tag| %>
									<!-- コントローラにパラメータを渡すtag_nameには、idではなくタグの名前を渡す必要がある -->
									<%= link_to search_result_path(tag_name: tag), class:"tag-label-link" do %>
										<span class="post-tag-text"><%= tag %>　></span>
									<% end %>
								<% end %>
							</div>
						</div>
					</div>

				<% end %>
			</div>
		</div>
	</div>
</div>