config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins

  # ユーザ用ルーティング
  devise_for :users

  resources :users, only: %i[show edit update] do
    get 'users/following', to: 'users#following', on: :member
    get 'users/follower', to: 'users#follower', on: :member
    get 'likes', to: 'likes#index', on: :member
  end
  get 'users/:id/exit' => 'users#exit', as: 'exit'
  get 'users/:id/follower' => 'users#follower', as: 'follower'
  get 'users/:id/following' => 'users#following', as: 'following'

  resources :post_gardens, only: %i[new create show edit update destroy] do
    resources :post_comments, only: %i[create destroy]
    post 'likes', to: 'likes#create', on: :member
    delete 'likes', to: 'likes#destroy', on: :member
    post 'send_images', to: 'post_gardens#send_images', on: :collection
  end
  root to: 'post_gardens#index'
  get 'about' => 'post_gardens#about', as: 'about'
  get 'post_gardens/:id/new_open_garden' => 'post_gardens#new_open_garden', as: 'new_open_garden'
  get 'search_result' => 'post_gardens#search_result', as: 'search_result'
  patch 'post_gardens/:id/delete_open_info' => 'post_gardens#delete_open_info', as: 'delete_open_info'

  resources :post_images, only: [:destroy]

  resources :open_days, only: %i[create update destroy]
  # resources :new_open_garden

  resources :relationships, only: [:create]
  delete 'relationships/:id' => 'relationships#destroy', as: 'unfollow'

  resources :reservations, only: %i[create show edit update]
  get 'reservations/new/:id' => 'reservations#new', as: 'new_reservation'
  get 'done' => 'reservations#done', as: 'done'
  get 'accept_reservations/:id' => 'reservations#accept_reservations', as: 'accept_reservations'
  get 'request_reservations/:id' => 'reservations#request_reservations', as: 'request_reservations'
  get 'approve_reservation/:id' => 'reservations#approve_reservation', as: 'approve_reservation'
  get 'approved/:id' => 'reservations#approved', as: 'approved'
  get 'cancel_reason/:id' => 'reservations#cancel_reason', as: 'cancel_reason'
  get 'canceled/:id' => 'reservations#canceled', as: 'canceled'

  resources :notifications, only: :index

  resources :search_plants, only: %i[new show create]
end

app/models/reservation.rb
# frozen_string_literal: true

class Reservation < ApplicationRecord
  enum request_status: { "未受付": 0, "承認": 1, "キャンセル": 2 }

  belongs_to :user
  belongs_to :post_garden

  has_many :notifications, dependent: :destroy

  # 予約リクエスト送付時の通知（予約者→所有者）
  def create_notification_reservation!(current_user)
    notification = current_user.active_notifications.new(
      reservation_id: id,
      post_garden_id: post_garden_id,
      visited_id: owner_id,
      action: 'reservation_request'
    )
    notification.save if notification.valid?
  end

  # 予約リクエスト承認時の通知（所有者→予約者）
  def approve_request_notification_reservation!(current_user)
    notification = current_user.active_notifications.new(
      reservation_id: id,
      post_garden_id: post_garden_id,
      visited_id: user_id,
      action: 'reservation_approve'
    )
    notification.save if notification.valid?
  end

  # 予約変更時の通知（予約者→所有者）
  def change_notification_reservation!(current_user)
    notification = current_user.active_notifications.new(
      reservation_id: id,
      post_garden_id: post_garden_id,
      visited_id: owner_id,
      action: 'reservation_change'
    )
    notification.save if notification.valid?
  end

  def cancel_notification_reservation!(current_user)
    # キャンセルしたのが予約者であれば、所有者に、所有者であれば予約者に通知を送る
    if current_user.id == user_id
      notification = current_user.active_notifications.new(
        reservation_id: id,
        post_garden_id: post_garden_id,
        visited_id: owner_id,
        action: 'reservation_cancel'
      )
    elsif current_user.id == owner_id
      notification = current_user.active_notifications.new(
        reservation_id: id,
        post_garden_id: post_garden_id,
        visited_id: user_id,
        action: 'reservation_cancel'
      )
    end
    notification.save if notification.valid?
  end
end

app/controllers/reservations_controller.rb
# frozen_string_literal: true

class ReservationsController < ApplicationController
  def new
    @reservation = Reservation.new
    @post_garden = PostGarden.find(params[:id])

    # イベント取得用
    @open_days = OpenDay.where(post_garden_id: params[:id])
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @user = current_user
    @open_day = OpenDay.find_by(id: params[:reservation][:id])

    if @reservation.r_start_datetime >= @open_day.start_time && @reservation.r_start_datetime <= @open_day.end_time && @reservation.r_end_datetime >= @open_day.start_time && @reservation.r_end_datetime <= @open_day.end_time

      if @reservation.save
        # メールと通知
        NotificationMailer.send_request_for_visit(@user, @reservation).deliver
        NotificationMailer.recieve_request_for_visit(@user, @reservation).deliver
        @reservation.create_notification_reservation!(current_user)
        redirect_to done_path
      else
        render 'new'
      end

    else
      redirect_to new_reservation_path(@reservation.post_garden_id)
      flash[:danger] = '指定された時間の中から開始時間と終了時間をお選びください'
    end
  end

  def done; end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def update
    @reservation = Reservation.find(params[:id])
    @user = User.find_by(id: @reservation.user_id)

    before_reservation_num = @reservation.reservation_num
    before_reservation_r_start_datetime = @reservation.r_start_datetime
    before_reservation_r_end_datetime = @reservation.r_end_datetime

    @reservation.update(reservation_params)

    # もし、人数、日付が変わっていたら、メールと通知
    if before_reservation_num != @reservation.reservation_num || before_reservation_r_start_datetime != @reservation.r_start_datetime || before_reservation_r_end_datetime != @reservation.r_end_datetime
      @reservation.update_attributes(request_status: 0)
      ReservationChangeMailer.send_request_for_visit(@user, @reservation).deliver
      ReservationChangeMailer.recieve_request_for_visit(@user, @reservation).deliver
      @reservation.change_notification_reservation!(current_user)
      redirect_to request_reservations_path(current_user.id)
    # 予約リクエスト承認時のメールと通知
    elsif @reservation.request_status == '承認'
      RequestApproveMailer.send_request_for_visit(@user, @reservation).deliver
      RequestApproveMailer.recieve_request_for_visit(@user, @reservation).deliver
      @reservation.approve_request_notification_reservation!(current_user)
      redirect_to accept_reservations_path(current_user.id)
    # 予約キャンセル時のメールと通知
    elsif @reservation.request_status == 'キャンセル'
      RequestCancelMailer.send_request_for_visit(@user, @reservation).deliver
      RequestCancelMailer.recieve_request_for_visit(@user, @reservation).deliver
      @reservation.cancel_notification_reservation!(current_user)
      redirect_to user_path(current_user.id)
    end
  end

  def request_reservations
    @reservations = Reservation.where(user_id: current_user.id).order(created_at: 'DESC').includes([post_garden: :user]).includes([post_garden: :post_images])
  end

  def accept_reservations
    @reservations = Reservation.where(owner_id: current_user.id).order(created_at: 'DESC').includes([:post_garden]).includes([:user])
  end

  def approve_reservation
    @reservation = Reservation.find(params[:id])
  end

  def approved
    @reservation = Reservation.find(params[:id])
  end

  def cancel_reason
    @reservation = Reservation.find(params[:id])
  end

  def canceled
    @reservation = Reservation.find(params[:id])
  end

  private

  def reservation_params
    params.require(:reservation).permit(:user_id, :post_garden_id, :r_start_datetime, :r_end_datetime, :reservation_name, :reservation_num, :reservation_message, :postal_code, :reservation_address, :entrance_fee, :announce, :owner_id, :owner_name, :request_status, :cancel_reason)
  end
end

app/helpers/reservations_helper.rb
# frozen_string_literal: true

module ReservationsHelper
end

app/views/reservations/accept_reservations.html.erb
<div class="container">
	<div class="row">

		<div class="col-xs-8 col-xs-offset-2">
			<div class="accept-reservations-index-title">
				<span class="accept-reservations-index-title-text"><strong><i class="fas fa-home"></i>公開中の庭園見学希望一覧</strong></span>
			</div>
		</div>

		<div class="col-xs-8 col-xs-offset-2">
			<div class="request-color-example">
				<span class="not-check-color-example"></span> •••未承認
				<span class="accept-color-example"></span> •••承認済
				<span class="cancel-color-example"></span> •••キャンセル済
			</div>
		</div>


		<div class="col-xs-8 col-xs-offset-2">
			<% @reservations.each do |reservation| %>

				<% if reservation.request_status == "未受付" %>
					<div class="panel panel-danger">
						<div class="panel-heading">
							予約者名：<%= reservation.reservation_name %>
							<span class="request-reservation-day">予約リクエスト受信日：<%= reservation.created_at.strftime("%Y年%m月%d日 %H時%M分") %></span>
						</div>

						<div class="panel-body">
							<h4 class="panel-title">
								予約日：<%= reservation.r_start_datetime.strftime("%Y年%m月%d日 %H時%M分") %>〜<%= reservation.r_end_datetime.strftime("%Y年%m月%d日 %H時%M分") %>
							</h4>

							<div class="row">
								<div class="panel-content">
									<div class="col-xs-2">
										<%= link_to post_garden_path(reservation.post_garden.id) do %>
											<%= attachment_image_tag reservation.post_garden.post_images[0], :garden_image, :fill, 80,80, format: 'jpg', class:"index-post-image" %>
										<% end %>
									</div>

									<div class="col-xs-2 request-reservation-content-position">
										<label class="request-reservation-num">訪問者</label><br>
										<span class="request-reservation-user-name">
											<%= attachment_image_tag reservation.user, :profile_image, :fill, 20,20, format: 'jpg', class:"index-profile-image" %>
											<%= reservation.user.user_name %>
										</span>
									</div>

									<div class="col-xs-2 request-reservation-content-position">
										<label class="request-reservation-num">予約人数</label><br>
										<span class="request-reservation-num"><%= reservation.reservation_num %>人</span>
									</div>

									<div class="col-xs-3 request-reservation-content-position">
										<label class="request-reservation-message">予約メッセージ</label><br>
										<span class="request-reservation-message"><%= reservation.reservation_message %></span>
									</div>
								</div>


								<div class="col-xs-3">
									<div class="detail-reservation request-reservation-content-position">
										<%= link_to "新規予約リクエスト", approve_reservation_path(reservation.id), class:"btn btn-danger" %>
									</div>
								</div>
							</div>

						</div>
					</div>

				<% elsif reservation.request_status == "承認" %>

					<div class="panel panel-success">
						<div class="panel-heading">
							予約者名：<%= reservation.reservation_name %>
							<span class="request-reservation-day">予約リクエスト受信日：<%= reservation.created_at.strftime("%Y年%m月%d日 %H時%M分") %></span>
						</div>

						<div class="panel-body">
							<h4 class="panel-title">
								予約日：<%= reservation.r_start_datetime.strftime("%Y年%m月%d日 %H時%M分") %>〜<%= reservation.r_end_datetime.strftime("%Y年%m月%d日 %H時%M分") %>
							</h4>

							<div class="row">
								<div class="panel-content">
									<div class="col-xs-2">
										<%= link_to post_garden_path(reservation.post_garden.id) do %>
											<%= attachment_image_tag reservation.post_garden.post_images[0], :garden_image, :fill, 80,80, format: 'jpg', class:"index-post-image" %>
										<% end %>
									</div>

									<div class="col-xs-2 request-reservation-content-position">
										<label class="request-reservation-num">訪問者</label><br>
										<span class="request-reservation-user-name">
											<%= attachment_image_tag reservation.user, :profile_image, :fill, 20,20, format: 'jpg', class:"index-profile-image" %>
											<%= reservation.user.user_name %>
										</span>
									</div>

									<div class="col-xs-2 request-reservation-content-position">
										<label class="request-reservation-num">予約人数</label><br>
										<span class="request-reservation-num"><%= reservation.reservation_num %>人</span>
									</div>

									<div class="col-xs-4 request-reservation-content-position">
										<label class="request-reservation-message">予約メッセージ</label><br>
										<span class="request-reservation-message"><%= reservation.reservation_message %></span>
									</div>
								</div>


								<div class="col-xs-2">
									<div class="detail-reservation request-reservation-content-position">
										<%= link_to "詳細", reservation_path(reservation.id), class:"btn btn-success" %>
									</div>
								</div>
							</div>

						</div>
					</div>

				<% elsif reservation.request_status == "キャンセル" %>

					<div class="panel panel-warning">
						<div class="panel-heading">
							予約者名：<%= reservation.reservation_name %>
							<span class="request-reservation-day">予約リクエスト受信日：<%= reservation.created_at.strftime("%Y年%m月%d日 %H時%M分") %></span>
						</div>

						<div class="panel-body">
							<h4 class="panel-title">
								予約日：<%= reservation.r_start_datetime.strftime("%Y年%m月%d日 %H時%M分") %>〜<%= reservation.r_end_datetime.strftime("%Y年%m月%d日 %H時%M分") %>
							</h4>

							<div class="row">
								<div class="panel-content">
									<div class="col-xs-2">
										<%= link_to post_garden_path(reservation.post_garden.id) do %>
											<%= attachment_image_tag reservation.post_garden.post_images[0], :garden_image, :fill, 80,80, format: 'jpg', class:"index-post-image" %>
										<% end %>
									</div>

									<div class="col-xs-2 request-reservation-content-position">
										<label class="request-reservation-num">訪問者</label><br>
										<span class="request-reservation-user-name">
											<%= attachment_image_tag reservation.user, :profile_image, :fill, 20,20, format: 'jpg', class:"index-profile-image" %>
											<%= reservation.user.user_name %>
										</span>
									</div>

									<div class="col-xs-2 request-reservation-content-position">
										<label class="request-reservation-num">予約人数</label><br>
										<span class="request-reservation-num"><%= reservation.reservation_num %>人</span>
									</div>

									<div class="col-xs-4 request-reservation-content-position">
										<label class="request-reservation-message">予約メッセージ</label><br>
										<span class="request-reservation-message"><%= reservation.reservation_message %></span>
									</div>
								</div>


								<div class="col-xs-2">
									<div class="detail-reservation request-reservation-content-position">
										<%= link_to "詳細", reservation_path(reservation.id), class:"btn btn-warning" %>
									</div>
								</div>
							</div>

						</div>
					</div>

				<% end %>

			<% end %>
		</div>
	</div>
</div>

app/views/reservations/approve_reservation.html.erb
<div class="container">
	<div class="row">

		<div class="col-xs-8 col-xs-offset-1">
			<div class="approve-reservation-title">
				<span class="approve-reservation-title-text"><strong><i class="fas fa-leaf"></i>庭園の訪問予約リクエスト</strong></span>
			</div>
		</div>

		<div class="row">
			<div class="col-xs-8 col-xs-offset-2">
				<div id="calendar-reservation"></div>
			</div>
		</div>

		<!-- どの投稿のカレンダーか判別するため、idをjqueryに渡している -->
		<div class="params_num_reservation" data-params="<%= @reservation.post_garden.id %>"></div>

		<div class="row">

			<div class="col-xs-6 col-xs-offset-3 approve-reservation-info">

				<div class="col-xs-10 col-xs-offset-1">
					<div class="approve-reservation-content">
						<span class="approve-reservation-content-text"><strong>ご予約内容</strong></span>
					</div>
				</div>

				<div class="col-xs-10 col-xs-offset-1">
					<label class="approve-reservation-datetime-text">◯ 予約時間</label><br>
					<%= @reservation.r_start_datetime.strftime("%Y年%m月%d日 %H時%M分") %>　〜　<%= @reservation.r_end_datetime.strftime("%Y年%m月%d日 %H時%M分") %>
				</div>


				<!-- 予約者名と人数 -->
				<div class="col-xs-3 col-xs-offset-1">
					<div class="approve-reservation-name">
						<label class="approve-reservation-name-text">◯ 予約者名</label><br>
						<%= @reservation.reservation_name %>様
					</div>
				</div>

				<div class="col-xs-5">
					<div class="approve-reservation-num">
						<label class="approve-reservation-num-text">◯ 予約人数（最大<%= @reservation.post_garden.open_max_number %>人）</label><br>
						<%= @reservation.reservation_num %>
					</div>
				</div>


				<!-- 予約メッセージ -->
				<div class="col-xs-9 col-xs-offset-1">
					<div class="field">
						<label class="reservation-message">◯ 予約メッセージ</label><br>
						<%= @reservation.reservation_message %>
					</div>
				</div>

			</div>
		</div>


		<!-- 予約内容確認事項 -->

		<div class="row">

			<div class="col-xs-9 col-xs-offset-1">

				<div class="approve-reservation-bottom-content">
					<span class="approve-reservation-bottom-content-text">◯ ご予約リクエストを受けたお庭はこちらです。</span>
				</div>

			</div>


			<div class="col-xs-10 col-xs-offset-1">

				<div id="map"></div>

					<script>
						var map;
						var tokyo = {lat: 35.6811673, lng: 139.7670516};

						function initMap(){

							var map = new google.maps.Map(document.getElementById('map'), {
				          	zoom: 15
				          	// center: marker
				      		});
				      		var latlng = new google.maps.LatLng(<%= @reservation.post_garden.latitude %>, <%= @reservation.post_garden.longitude %>);
				      		map.setCenter(latlng);

							(function(){
								var contentString = '<%= attachment_image_tag @reservation.post_garden.post_images[0], :garden_image, :fill, 100, 100, format: 'jpg' %>' + '<br><br><br>' + '<strong>住所</strong>' + '<br>' + '〒<%= @reservation.postal_code %>' + '<br>' + '<%= @reservation.reservation_address %>' + '<br>' + '<strong>投稿者</strong>' + '<br>' + '<%= @reservation.owner_name %>' + '<br>' + '<strong>使用している庭木</strong>' + '<br>' + '<% @reservation.post_garden.planted_gardens.each do |planted_garden| %><%= planted_garden.plant_name %><% end %>'+ '<br>' + '<%= @reservation.post_garden.tag_list %>' + '<br>' + '<%= link_to post_garden_path(@reservation.post_garden.id) do %><span class="link">詳細へ</span><% end %>';
								var infowindow = new google.maps.InfoWindow({
									content: contentString,
									maxWidth: 1000,
								});

								var marker = new google.maps.Marker({
									position:{lat: <%= @reservation.post_garden.latitude %>, lng: <%= @reservation.post_garden.longitude %>},
									map: map,
									title: contentString
									});

								marker.addListener('click', function(){
									infowindow.open(map, marker);
								});
							})();
						};
					</script>
			</div>

			<div class="col-xs-10 col-xs-offset-1 reservation-info">

				<!-- 住所 -->
				<div class="col-xs-8">
					<label class="reservation-content-address">・住所</label>
						<span class="reservation-content-postal-code-text">〒<%= @reservation.postal_code %></span>
						<span class="reservation-content-address-text"><%= @reservation.reservation_address %></span>
				</div>

				<!-- 入場料 -->
				<div class="col-xs-8 reservation-content-entrance-fee-position">
					<label class="reservation-content-entrance-fee">・入場料</label>
					<span class="reservation-content-entrance-fee-text"><%= @reservation.entrance_fee %>円</span>
				</div>


				<!-- 注意事項 -->
				<div class="col-xs-8">
					<label class="reservation-content-entrance-fee">・注意事項</label><br>
					<div class="reservation-content-announce-text">
						<%= @reservation.announce %>
					</div>
				</div>

				<div class="col-xs-1 col-xs-offset-2">
					<%= link_to "詳細", post_garden_path(@reservation.post_garden_id), class:"btn btn-primary" %>
				</div>

			</div>

		</div>

		<div class="row">
			<div class="reservation-confirm">
				<div class="col-xs-2 col-xs-offset-4 reservation-bottom">

					<!-- リクエストステータスを"承認"に変更 -->
					<%= form_for @reservation, url:reservation_path, method: :patch do |f| %>
						<%= f.hidden_field :request_status, :value => "承認" %>
						<%= f.submit "リクエストを承認する", class:"btn btn-success", data: {confirm: "リクエストを承認します。よろしいですか？"} %>
					<% end %>

				</div>

				<div class="col-xs-2 col-xs-offset-3">
					<!-- キャンセル画面へ -->
					<%= link_to "キャンセルする", cancel_reason_path(@reservation.id), class:"btn btn-warning" %>
				</div>
			</div>
		</div>

	</div>
</div>

<!-- Google map API用 -->
<script async defer src="https://maps.google.com/maps/api/js?key=<%= ENV['GOOGLE_API_KEY'] %>&callback=initMap&language=ja"></script>

app/views/reservations/cancel_reason.html.erb
<div class="container">
	<div class="row">

		<div class="reservation-cancel-reason-title">
			<span class="reservation-cancel-reason-title-text"><strong>キャンセルを確定するには、キャンセル理由をご記入の上、下部のボタンを押してください</strong></san>
		</div>


		<div class="row">
			<div class="col-xs-6 col-xs-offset-2">
				<div class="reservation-confirm">

					<!-- リクエストステータスを"キャンセル"に変更 -->
					<%= form_for @reservation, url:reservation_path, method: :patch do |f| %>

						<%= f.hidden_field :request_status, :value => "キャンセル" %>

						<div class="field">
							<label class="reservation-cancel-reason">◯ キャンセル理由</label><br>
							<%= f.text_area :cancel_reason, class:"col-auto form-control form-control-lg w-100" %>
						</div>

						<div class="col-xs-6 col-xs-offset-3 reservation-cancel-confirm">
							<%= f.submit "リクエストをお断りする", "data-confirm" => "予約をお断りします。よろしいですか？", class:"btn btn-warning" %>
						</div>
					<% end %>
				</div>
			</div>
		</div>


	</div>
</div>

app/views/reservations/done.html.erb
<div class="contaner">
	<div class="row">

		<div class="col-xs-4 col-xs-offset-4">
			<div class="done-reservation-title-position">
				<span class="done-reservation-title"><i class="fas fa-user-check"></i>予約リクエストが送信されました。</span>
			</div>

			<div class="done-reservation-text-position">
				<span class="done-reservation-text">リクエストが承認されるまでお待ちください。<br>予約リクエストは、<%= link_to "予約一覧", request_reservations_path(current_user.id) %>からご確認ください。</span>
			</div>
		</div>

	</div>
</div>

app/views/reservations/show.html.erb
<div class="container">
	<div class="row">

		<div class="col-xs-10 col-xs-offset-1 reservation-show-all-title">
			<% if @reservation.request_status == "未受付" %>
				<div class="reservation-show-not-yet-title">
					<span class="reservation-show-not-yet-text"><strong><i class="fas fa-spinner"></i>予約リクエスト中</strong></span>
				</div>
			<% elsif @reservation.request_status == "承認" %>
				<div class="reservation-show-approved-title">
					<span class="reservation-show-approved-text"><strong><i class="far fa-check-circle"></i>この予約は確定されています</strong></span>
				</div>
			<% elsif @reservation.request_status == "キャンセル" %>
				<div class="reservation-show-canceled-title">
					<span class="reservation-show-canceled-text"><strong><i class="fas fa-ban"></i>この予約はキャンセルされています</strong></span>
				</div>
			<% end %>
		</div>

		<div class="row">
			<div class="col-xs-10 col-xs-offset-1 reservation-show-bg-color">

				<div class="reservation-show-content-title">
					<span class="reservation-show-content-title-text"><strong>予約詳細</strong></span>
				</div>


				<!-- 予約者名と人数 -->
				<div class="col-xs-2 col-xs-offset-1">
					<label class="reservation-show-name">◯ 予約者名</label><br>
					<span class="reservation-show-name-text"><%= @reservation.reservation_name %></span>
				</div>

				<div class="col-xs-3">
					<label class="reservation-show-num">◯ 予約人数（最大<%= @reservation.post_garden.open_max_number %>人）</label><br>
					<span class="reservation-show-num-text"><%= @reservation.reservation_num %>人</span>
				</div>


				<!-- 住所 -->
				<div class="col-xs-6">
					<label class="reservation-show-address">◯ 住所</label><br>
					<span class="reservation-show-address-text">〒<%= @reservation.postal_code %>
					<%= @reservation.reservation_address %></span>
				</div>


				<!-- 予約時間 -->
				<div class="col-xs-6 col-xs-offset-1">
					<label class="reservation-show-datetime">◯ 予約時間</label><br>
					<span class="reservation-show-datetime-text"><%= @reservation.r_start_datetime.strftime("%Y年%m月%d日 %H時%M分") %>　〜　<%= @reservation.r_end_datetime.strftime("%Y年%m月%d日 %H時%M分") %></span>
				</div>


				<!-- 入場料 -->
				<div class="col-xs-2">
					<label class="reservation-show-entrance-fee">◯ 入場料</label><br>
					<span class="reservation-show-entrance-fee-text"><%= @reservation.entrance_fee %>円</span>
				</div>


				<!-- 予約メッセージ -->
				<div class="col-xs-4 col-xs-offset-1">
					<label class="reservation-show-message">◯ 予約メッセージ</label><br>
					<span class="reservation-show-message-text"><%= @reservation.reservation_message %></span>
				</div>


				<!-- 注意事項 -->
				<div class="col-xs-4">
					<label class="reservation-show-announce">◯ 注意事項</label><br>
					<span class="reservation-show-announce-text"><%= @reservation.announce %></span>
				</div>


				<!-- 詳細へ -->
				<div class="col-xs-3 reservation-show-post-detail">
					<%= attachment_image_tag @reservation.post_garden.post_images[0], :garden_image, :fill, 50,50, format: 'jpg', class:"index-post-image reservation-show-post-detail-image" %>
					<%= link_to "詳細", post_garden_path(@reservation.post_garden_id), class:"btn btn-primary" %>
				</div>


			</div>
		</div>


		<div class="row">
			<div class="col-xs-10 col-xs-offset-1">

				<div id="map"></div>

					<script>
						var map;
						var tokyo = {lat: 35.6811673, lng: 139.7670516};

						function initMap(){

							var map = new google.maps.Map(document.getElementById('map'), {
				          	zoom: 15
				          	// center: marker
				      		});
				      		var latlng = new google.maps.LatLng(<%= @reservation.post_garden.latitude %>, <%= @reservation.post_garden.longitude %>);
				      		map.setCenter(latlng);

							(function(){
								var contentString = '<div class="row">' + '<div class="col-xs-6">' + '<%= attachment_image_tag @reservation.post_garden.post_images[0], :garden_image, :fill, 100, 100, format: 'jpg', class:"index-post-image" %>' + '</div>' + '<div class="col-xs-6">' + '<strong>投稿者</strong>' + '<br>' + '<%= @reservation.owner_name %>' + '<br>' + '<% @reservation.post_garden.tag_list.each do |tag| %>' + '<span class="post-tag-text"><%= tag %></span>' + '<% end %>' + '<p>' + '<%= link_to post_garden_path(@reservation.post_garden.id) do %><span class="btn btn-primary btn-sm">詳細へ</span><% end %>' + '</p>' + '</div>';
								var infowindow = new google.maps.InfoWindow({
									content: contentString,
									maxWidth: 1000,
								});

								var marker = new google.maps.Marker({
									position:{lat: <%= @reservation.post_garden.latitude %>, lng: <%= @reservation.post_garden.longitude %>},
									map: map,
									title: contentString
									});

								marker.addListener('click', function(){
									infowindow.open(map, marker);
								});
							})();
						};
					</script>
			</div>

		</div>


		<!-- 自身でリクエストした予約は編集可能。キャンセルした予約は、編集できないように -->
		<% if @reservation.user_id == current_user.id %>
			<% if @reservation.request_status == "未受付" || @reservation.request_status == "承認" %>
				<div class="col-xs-2 col-xs-offset-5 reservation-bottom">
					<%= link_to "予約内容変更", edit_reservation_path(@reservation.id), class:"btn btn-primary" %>
				</div>

				<div class="col-xs-2 col-xs-offset-2">
					<%= link_to "キャンセルする", cancel_reason_path(@reservation.id), class:"btn btn-warning" %>
				</div>
			<% end %>

		<% elsif @reservation.owner_id == current_user.id %>
			<% if @reservation.request_status == "未受付" || @reservation.request_status == "承認" %>
			<div class="col-xs-2 col-xs-offset-9 reservation-bottom">
				<%= link_to "キャンセルする", cancel_reason_path(@reservation.id), class:"btn btn-warning reservation-show-button" %>
			</div>
			<% end %>
		<% end %>

	</div>
</div>

<!-- Google map API用 -->
<script async defer src="https://maps.google.com/maps/api/js?key=<%= ENV['GOOGLE_API_KEY'] %>&callback=initMap&language=ja"></script>