config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins

  # ユーザ用ルーティング
  devise_for :users

  resources :users, only: %i[show edit update] do
    get 'users/following', to: 'users#following', on: :member
    get 'users/follower', to: 'users#follower', on: :member
    get 'likes', to: 'likes#index', on: :member
  end
  get 'users/:id/exit' => 'users#exit', as: 'exit'
  get 'users/:id/follower' => 'users#follower', as: 'follower'
  get 'users/:id/following' => 'users#following', as: 'following'

  resources :post_gardens, only: %i[new create show edit update destroy] do
    resources :post_comments, only: %i[create destroy]
    post 'likes', to: 'likes#create', on: :member
    delete 'likes', to: 'likes#destroy', on: :member
    post 'send_images', to: 'post_gardens#send_images', on: :collection
  end
  root to: 'post_gardens#index'
  get 'about' => 'post_gardens#about', as: 'about'
  get 'post_gardens/:id/new_open_garden' => 'post_gardens#new_open_garden', as: 'new_open_garden'
  get 'search_result' => 'post_gardens#search_result', as: 'search_result'
  patch 'post_gardens/:id/delete_open_info' => 'post_gardens#delete_open_info', as: 'delete_open_info'

  resources :post_images, only: [:destroy]

  resources :open_days, only: %i[create update destroy]
  # resources :new_open_garden

  resources :relationships, only: [:create]
  delete 'relationships/:id' => 'relationships#destroy', as: 'unfollow'

  resources :reservations, only: %i[create show edit update]
  get 'reservations/new/:id' => 'reservations#new', as: 'new_reservation'
  get 'done' => 'reservations#done', as: 'done'
  get 'accept_reservations/:id' => 'reservations#accept_reservations', as: 'accept_reservations'
  get 'request_reservations/:id' => 'reservations#request_reservations', as: 'request_reservations'
  get 'approve_reservation/:id' => 'reservations#approve_reservation', as: 'approve_reservation'
  get 'approved/:id' => 'reservations#approved', as: 'approved'
  get 'cancel_reason/:id' => 'reservations#cancel_reason', as: 'cancel_reason'
  get 'canceled/:id' => 'reservations#canceled', as: 'canceled'

  resources :notifications, only: :index

  resources :search_plants, only: %i[new show create]
end

app/models/post_garden.rb
# frozen_string_literal: true

class PostGarden < ApplicationRecord
  enum open_prefecture: { "北海道": 0, "青森県": 1, "岩手県": 2, "宮城県": 3, "秋田県": 4, "山形県": 5, "福島県": 6, "茨城県": 7, "栃木県": 8, "群馬県": 9, "埼玉県": 10, "千葉県": 11, "東京都": 12, "神奈川県": 13, "新潟県": 14, "富山県": 15, "石川県": 16, "福井県": 17, "山梨県": 18, "長野県": 19, "岐阜県": 20, "静岡県": 21, "愛知県": 22, "三重県": 23, "滋賀県": 24, "京都府": 25, "大阪府": 26, "兵庫県": 27, "奈良県": 28, "和歌山県": 29, "鳥取県": 30, "島根県": 31, "岡山県": 32, "広島県": 33, "山口県": 34, "徳島県": 35, "香川県": 36, "愛媛県": 37, "高知県": 38, "福岡県": 39, "佐賀県": 40, "長崎県": 41, "熊本県": 42, "大分県": 43, "宮崎県": 44, "鹿児島県": 45, "沖縄県": 46 }
  enum open_status: { "非公開": 0, "公開": 1 }

  validates :post_content, presence: true, length: { maximum: 200 }

  belongs_to :user

  has_many :post_images, dependent: :destroy
  accepts_nested_attributes_for :post_images, reject_if: :all_blank, allow_destroy: true
  accepts_attachments_for :post_images, attachment: :garden_image

  has_many :planted_gardens
  accepts_nested_attributes_for :planted_gardens, reject_if: :all_blank, allow_destroy: true

  has_many :open_days, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :reservations, dependent: :destroy

  # タグ付用記述
  acts_as_taggable

  # 住所入力時に緯度経度も自動で保存
  geocoded_by :address
  after_validation :geocode

  # 通知用記述
  has_many :notifications, dependent: :destroy

  # いいねが１投稿につき１人１回
  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  # 以下通知機能のメソッド
  # いいねの通知機能
  def create_notification_like!(current_user)
    # 既に「いいねされているか検索
    temp = Notification.where(['visitor_id = ? and visited_id = ? and post_garden_id = ? and action = ? ', current_user.id, user_id, id, 'like'])

    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_garden_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は、通知済とする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  # コメントの通知機能
  def create_notification_comment!(current_user, post_comment_id)
    # 自分以外にコメントしている人を全て取得し、全員に通知を送る
    temp_ids = PostComment.select(:user_id).where(post_garden_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, post_comment_id, temp_id['user_id'])
    end

    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    if temp_ids.blank?
      save_notification_comment!(current_user, post_comment_id, user_id)
 end
  end

  def save_notification_comment!(current_user, post_comment_id, visited_id)
    # コメントは複数回することができるため、一つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      post_garden_id: id,
      post_comment_id: post_comment_id,
      visited_id: visited_id,
      action: 'comment'
    )

    # 自分の投稿に対するコメントは通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/post_gardens_controller.rb
# frozen_string_literal: true

class PostGardensController < ApplicationController
  def new
    @post_garden = PostGarden.new

    @post_image = @post_garden.post_images.build
    @planted_garden = @post_garden.planted_gardens.build
  end

  def send_images
    # postアクションなので、strongparameterを設定する必要がある
    send_images = Vision.get_image_ajax(send_image_params[:image])
    translations = []
    send_images.each do |send_image|
      translate_result = Translation.get_label_data(send_image['description'])
      add_translations = { 'keyword' => translate_result.to_s }
      translations.push(add_translations)
    end
    render json: translations
  end

  def create
    @post_garden = PostGarden.new(post_garden_params)
    @post_garden.user_id = current_user.id
    if @post_garden.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def index
    # 新着の投稿
    @post_gardens = PostGarden.all.order(created_at: :desc).limit(12).includes([:user]).includes([:post_images]).includes([:taggings])
    # いいね数順
    @rank_orders = PostGarden.all.order(likes_count: :desc).limit(12).includes([:user]).includes([:post_images]).includes([:taggings])

    if user_signed_in?
      # フォローしているユーザの投稿
      @followings = Relationship.where(user_id: current_user.id)
      @following_posts = []
      # フォローしている人１人ずつに対して
      @followings.each do |follow|
        posts = PostGarden.where(user_id: follow.follow_id).includes([:user]).includes([:post_images]).includes([:taggings])
        @following_posts.concat(posts)
      end
      # フォローしているユーザの全投稿を並び替える
      @order_following_posts = @following_posts.sort_by!(&:created_at).reverse.slice(0..11)
    end

    # 公開している庭一覧（Googlemapにピンを立てる）
    @open_gardens = PostGarden.where(open_status: 1)
    # 新着公開中庭園
    @open_gardens_side = PostGarden.where(open_status: 1).limit(3).order('created_at DESC').includes([:post_images])

    # よく使うタグを取ってくる（デフォルトで20件）
    @tags = ActsAsTaggableOn::Tag.most_used
  end

  def search_result
    # 検索パラメータはapplicationcontrollerで設定済
    # よく使うタグを取ってくる（デフォルトで20件）
    @tags = ActsAsTaggableOn::Tag.most_used

    # タグをクリックしたときの検索結果
    @post_gardens = PostGarden.all.includes([:post_images]).includes([:user]).includes([:taggings])
    @post_gardens = if params[:tag_name]
                      @post_gardens.tagged_with(params[:tag_name].to_s)
                    else
                      @search.result(distinct: true)
                    end
    # 新着公開中庭園
    @open_gardens_side = PostGarden.where(open_status: 1).limit(3).order('created_at DESC').includes([:post_images])
  end

  def show
    @post_garden = PostGarden.find(params[:id])
    @post_comments = PostComment.where(post_garden_id: @post_garden.id).includes([:user])
    @user = User.find_by(id: @post_garden.user_id)
    @post_comment = PostComment.new
    @reservation = Reservation.new

    # イベント取得用
    @open_days = OpenDay.where(post_garden_id: params[:id])
  end

  def edit
    @post_garden = PostGarden.find(params[:id])
  end

  def update
    @post_garden = PostGarden.find(params[:id])
    if @post_garden.update(post_garden_params)
      redirect_to post_garden_path(params[:id])
    else
      render 'edit'
    end
  end

  def destroy
    @post_garden = PostGarden.find(params[:id])
    @post_garden.destroy
    redirect_to user_path(current_user.id)
  end

  def new_open_garden
    @post_garden = PostGarden.find(params[:id])
    @open_day = OpenDay.new

    # idの情報は、更新を押した時に得られる。まだ取得できないので、空でインスタンスを作成しておく
    @open_day_updates = OpenDay.new

    # イベント取得用
    @open_days = OpenDay.where(post_garden_id: params[:id])
  end

  def delete_open_info
    @post_garden = PostGarden.find(params[:id])
    # 日程を全て削除
    @open_days = OpenDay.where(post_garden_id: @post_garden.id)

    @open_days.each(&:destroy)

    @post_garden.update_attributes(open_status: 0)
    redirect_to post_garden_path(params[:id])
  end

  def about; end

  private

  def post_garden_params
    params.require(:post_garden).permit(:post_content, :place, :area, :price, :problem, :solution, :open_status, :open_postal_code, :open_prefecture, :address, :latitude, :longitude, :open_max_number, :open_entrance_fee, :open_announce, :tag_list, post_images_attributes: %i[id garden_image _destroy], planted_gardens_attributes: %i[id plant_name plant_number _destroy])
  end

  def send_image_params
    params.permit(:image)
  end
end

app/helpers/post_gardens_helper.rb
# frozen_string_literal: true

module PostGardensHelper
end

app/views/post_gardens/_planted_garden_fields.html.erb
<div class="nested-fields">
	<div class="form-group">

		<div class="col-xs-3">
			<%= f.text_field :plant_name, class:"form-control plant_name_field" %>
		</div>
		<%= link_to_remove_association "削除", f, class:"btn btn-danger btn-sm" %>
		
	</div>
</div>

app/views/post_gardens/_post_image_fields.html.erb
<div class="col-xs-4">
	<div class="nested-fields">
		<div class="form-group new-post-image-box">

			<!-- // id "file"で、fileとdivを紐付けクリック時に連動 -->
            <div class="new_img_field" onClick="$('.new-post-image').click()">

                <div class="row">
                    <div class="col-xs-7 col-xs-offset-1">
                        <p class="new-image-text">クリックして画像を選択してください</p>
                    </div>
                    <div class="col-xs-4">
                        <i class="fas fa-image"></i>
                    </div>
                </div>

            </div>

            <div class="new-post-image-preview">
	            <!-- // id "file"をつけ、「display:none;」で隠す -->
	            <%= f.attachment_field :garden_image, direct: true, class:"new-post-image", style:"display:none;" %>
	        </div>

	        <div class="auto-keyword">
	        	<p class="auto-keyword-title">こんなタグをつけませんか？</p>
	        		<span class="auto-keyword-text-0 label label-info"></span>
	        		<span class="auto-keyword-text-1 label label-info"></span>
	        		<span class="auto-keyword-text-2 label label-info"></span>
	        		<span class="auto-keyword-text-3 label label-info"></span>
	        		<span class="auto-keyword-text-4 label label-info"></span>
	        </div>

			<%= link_to_remove_association "削除", f, class:"btn btn-danger btn-sm new-post-image-delete-position" %>

		</div>
	</div>
</div>

app/views/post_gardens/edit.html.erb
<div class="container">
	<div class="row">

		<%= form_for(@post_garden) do |f| %>

			<div class="row">
				<% @post_garden.post_images.each do |post_image| %>

					<div class="col-xs-3">
						<%= attachment_image_tag post_image, :garden_image, :fill, 150, 150, format: 'jpg', fallback: "no_image.jpg" %>
						<%= link_to "削除", post_image_path(post_image.id), method: :delete %>
					</div>
				<% end %>
			</div>

			<%= f.fields_for :post_images do |post_image| %>

				<%= render 'post_image_fields', f: post_image %>
			<% end %>
			<div class="links">
				<%= link_to_add_association "追加", f, :post_images %>
			</div>

			<!-- 画像投稿 -->

			<!-- 投稿内容 -->
			<div class="field">
				<label class="post_content-text">投稿内容</label>
				<%= f.text_area :post_content, class:"col-auto form-control form-control-lg w-100" %>
			</div>

			<!-- 場所 -->
			<div class="field">
				<label class="place-text">場所</label>
				<%= f.text_field :place, class:"col-auto form-control form-control-lg w-100", placeholder: "東京都品川区" %>
			</div>

			<!-- タグ -->
			<div class="field">
				<label class="tag-text">タグ</label>
				<%= f.text_field :tag_list, value: @post_garden.tag_list.join(","), 'data-role':'tagsinput', class:"col-auto form-control form-control-lg w-100", placeholder: "登録したいキーワードを入れてください。2つ以上の時はスペースを開けてください。" %>
			</div>

			<!-- 庭の広さ -->
			<div class="field">
				<label class="area-text">庭の広さ</label>
				<%= f.text_field :area, class:"col-auto form-control form-control-lg w-100", placeholder: "5m2" %>
			</div>

			<!-- かかった経費 -->
			<div class="field">
				<label class="price-text">かかった経費</label>
				<%= f.text_field :price, class:"col-auto form-control form-control-lg w-100", placeholder: "15,000円" %>
			</div>

			<!-- 使った庭木 -->
			<div class="field">
				<label class="price-text">使った庭木</label>
				<%= f.fields_for :planted_gardens do |planted_garden| %>
				<%= render 'planted_garden_fields', f: planted_garden %>
				<% end %>

				<div class="links">
					<%= link_to_add_association "追加", f, :planted_gardens %>
				</div>
				
			</div>

			<!-- 問題点（害虫、病気等） -->
			<div class="field">
				<label class="problem-text">問題点（害虫、病気等）</label>
				<%= f.text_area :problem, class:"col-auto form-control form-control-lg w-100", placeholder: "ハダニが多い。うどんこ病になってしまった。" %>
			</div>

			<!-- 解決策 -->
			<div class="field">
				<label class="solution-text">解決策</label>
				<%= f.text_area :solution, class:"col-auto form-control form-control-lg w-100", placeholder: "殺虫殺菌スプレー剤の「ベニカXスプレー」、「ベニカXファインスプレー」を散布しました" %>
			</div>





			<div class="row">
				<%= f.submit "更新する", class:"col-xs-3 col-xs-offset-2 btn btn-primary" %>
			</div>


		<% end %>

		<div class="post-delete">
			<%= link_to "削除", post_garden_path(@post_garden.id), method: :delete,"data-confirm" => "投稿に関連する情報も全て削除されます。よろしいですか？" %>
		</div>
	</div>
</div>

app/views/post_gardens/search_result.html.erb
<div class="container">
	<div class="row">

		<%= render 'layouts/sidemenu' %>

		<div class="col-xs-10 side-menu-left-line">

			<!-- 検索結果 -->
			<div class="row">

				<div class="col-xs-12 search-result-title">
					<!-- タグをクリックした時と検索ボックスに単語を入れた時の条件分岐 -->
					<% if params[:tag_name].nil? %>
						<span class="search-result-text"><strong>"<%= params[:q][:post_content_or_place_or_problem_or_solution_or_tags_name_or_planted_gardens_plant_name_cont] %>"の検索結果 <%= @post_gardens.count %>件</strong></span>
					<% else %>
						<span class="search-result-text"><strong>"<%= params[:tag_name] %>"のタグを持つ投稿 <%= @post_gardens.count %>件</strong></span>
					<% end %>
				</div>
			</div>

			<div class="row">
				<div class="new-post-index">

					<% @post_gardens.each do |post_garden| %>

						<div class="col-xs-3">
							<%= link_to post_garden_path(post_garden.id) do %>
								<%= attachment_image_tag post_garden.post_images[0], :garden_image, :fill, 200,200, format: 'jpg', class:"index-post-image" %>
							<% end %>

							<div class="post-index">
								<div class="index-profile-image-position">
									<%= link_to user_path(post_garden.user.id), class:"profile-image-link" do %>
										<%= attachment_image_tag post_garden.user, :profile_image, :fill, 30,30, format: 'jpg', class:"index-profile-image" %>
										<span class="profile-image-name"><%= post_garden.user.user_name %></span>
									<% end %>
								</div>

								<div class="tags-list-index">
									<% post_garden.tag_list.each do |tag| %>
										<!-- コントローラにパラメータを渡すtag_nameには、idではなくタグの名前を渡す必要がある -->
										<%= link_to search_result_path(tag_name: tag), class:"tag-label-link" do %>
											<span class="post-tag-text"><%= tag %>　></span>
										<% end %>
									<% end %>
								</div>
							</div>
						</div>

					<% end %>

				</div>

			</div>

		</div>
	</div>

</div>

app/views/post_gardens/show.html.erb
<div class="container position-adjust">

	<div class="row position-adjust">

		<div class="col-xs-10 col-xs-offset-1">

			<div class="col-xs-6">

       			<!-- data-indexでJsにデータを渡している。$('.slides').data('index')で値が取れる -->
       			<div class="slides" data-index="<%= @post_garden.post_images.length %>">

					<% @post_garden.post_images.each_with_index do |post_image, i| %>

						<% if i == 0 %>
							<div class="slide active">
								<%= attachment_image_tag post_image, :garden_image, :fill, 400,400, format: 'jpg', class:"show-post-image" %>
							</div>
						<% else %>
							<div class="slide">
								<%= attachment_image_tag post_image, :garden_image, :fill, 400,400, format: 'jpg', class:"show-post-image" %>
							</div>
						<% end %>

					<% end %>
				</div>


				<!-- 画像切り替え用矢印 -->
				<div class="change-btn-wrapper">
	          		<span class="change-btn prev-btn"><i class="far fa-arrow-alt-circle-left"></i></span>
	          		<span class="change-btn next-btn"><i class="far fa-arrow-alt-circle-right"></i></span>
       			</div>

				<!-- いいねボタン -->
				<div id="likes_buttons_<%= @post_garden.id %>">
					<%= render partial: 'likes/like', locals: {post_garden: @post_garden} %>
				</div>


			</div>


			<!-- 写真右の項目 -->

			<!-- 投稿者情報 -->
			<div class="col-xs-6">

				<!-- 場所 -->
				<div class="post-place">
					<span class="post-place-text"><%= @post_garden.place %></span>

					<!-- 自ユーザならば、投稿の編集 -->
					<% if user_signed_in? %>
						<% if @user.id == current_user.id %>

							<%= link_to "投稿の編集", edit_post_garden_path(@post_garden.id), class:"btn btn-primary edit-post-garden-text" %>

						<% end %>
					<% end %>

				</div>

				<div class="profile-image-box">
					<%= attachment_image_tag @user, :profile_image, :fill, 80,80, format: 'jpg', class:"show-profile-image" %>
					<%= link_to user_path(@post_garden.user.id), class:"profile-link" do %>
						<span class="show-profile-name"><strong><%= @user.user_name %></strong></span>
					<% end %>
				</div>


				<!-- 使った庭木 -->
				<div class="row">
					<div class="col-xs-10">

						<div class="post-planted-garden">
							<span class="post-planted-garden-title"><i class="fas fa-tree"></i><strong>使用した庭木</strong></span>
						</div>

						<div class="post-planted-garden-content">
							<% @post_garden.planted_gardens.each do |planted_garden| %>
								<span class="post-planted-garden-text"><%= planted_garden.plant_name %>  /</span>
							<% end %>
						</div>

					</div>
				</div>

				<!-- タグ -->
				<div class="row">
					<div class="col-xs-10">

						<div class="post-tag">
							<span class="post-tag-title"><i class="fas fa-tag"></i><strong>タグ</strong></span>
						</div>

						<div class="post-tag-content">
							<% @post_garden.tag_list.each do |tag| %>
								<%= link_to search_result_path(tag_name: tag), class:"tag-label-link" do %>
									<span class="post-tag-text-show"><%= tag %>　></span>
								<% end %>
							<% end %>
						</div>

					</div>

				</div>

				<!-- 面積 -->
				<div class="row">
					<div class="col-xs-5">

						<div class="post-area">
							<span class="post-area-title"><i class="fas fa-layer-group"></i><strong>面積</strong></span>
						</div>

						<div class="post-area-content">
							<span class="post-area-text"><%= @post_garden.area %></span>
						</div>

					</div>


					<!-- 経費 -->
					<div class="col-xs-5">

						<div class="post-expence">
							<span class="post-expence-title"><i class="fas fa-dollar-sign"></i><strong>経費</strong></span>
						</div>

						<div class="post-expence-content">
							<span class="post-expence-text"><%= @post_garden.price %>円</span>
						</div>

					</div>
				</div>



			</div>
		</div>


		<!-- 写真より下の項目 -->

		<!-- 問題点 -->
		<div class="row">

			<div class="col-xs-6 col-xs-offset-1">

				<div class="post-problem">
					<span class="post-problem-title"><i class="fas fa-exclamation-triangle"></i><strong>困ったこと</strong></span>
				</div>

				<div class="post-problem-content">
					<span class="post-problem-text"><%= @post_garden.problem %></span>
				</div>

			</div>
		</div>


		<!-- 解決策 -->
		<div class="row">
			<div class="col-xs-6 col-xs-offset-1">

				<div class="post-solution">
					<span class="post-solution-title"><i class="far fa-lightbulb"></i><strong>解決策</strong></span>
				</div>

				<div class="post-solution-content">
					<span class="post-solution-text"><%= @post_garden.solution %></span>
				</div>
			</div>
		</div>


		<!-- コメント欄 -->
		<div class="row">
			<div class="top-line-of-comment"></div>
			<div class="col-xs-6">

				<p class="comment-title">コメント一覧</p>

				<!-- コメント表示 -->
				<% if @post_comments.any? %>

					<% @post_comments.each do |post_comment| %>

					<div class="row">
						<div class="col-xs-2 col-xs-offset-2">
							<div class="comment-image-position">
								<%= attachment_image_tag post_comment.user, :profile_image, :fill, 60,60, format: 'jpg', class:"show-profile-image" %>
							</div>
						</div>

						<div class="col-xs-8">
							<div class="comment-user-name">
								<span class="comment-user-name-text"><strong><%= post_comment.user.user_name %></strong>

									<% if user_signed_in? %>
										<% if post_comment.user_id == current_user.id %>
											<%= link_to post_garden_post_comment_path(post_comment.id), method: :delete, class:"comment-delete" do %>
												<i class="fas fa-trash-alt"></i>
											<% end %>
										<% end %>
									<% end %>
								</span>
							</div>

							<div class="comment-content">
								<%= post_comment.comment_content %>
							</div>

						</div>
					</div>

					<% end %>

				<% else %>

					<span class="not-yet-comment">まだコメントはありません</span>

				<% end %>

				<!-- コメント入力 -->
				<% if user_signed_in? %>
					<div class="row">
						<div class="col-xs-8 col-xs-offset-4">
							<div class="comment-input">
								<%= form_for @post_comment, url: post_garden_post_comments_path(@post_garden) do |f| %>

									<%= f.text_area :comment_content, class:"form-control", placeholder:"コメントしよう！" %>

									<div class="comment-button">
										<%= f.submit "コメントする", class:"btn btn-primary pull-right btn-sm" %>
									</div>

								<% end %>
							</div>
						</div>
					</div>
				<% end %>

			</div>

			<!-- 予約用カレンダーの表示 -->
			<div class="col-xs-4 reserve-box">

				<% if @post_garden.open_status == "公開" %>
					<div class="open-status-box">
						<span class="open-status-text">公開中</span>
					</div>
				<% else %>
					<div class="not-open-status-box">
						<span class="not-open-status-text">非公開</span>
					</div>
				<% end %>


				<% if user_signed_in? %>
					<% if @user.id == current_user.id && @post_garden.open_status == "非公開" %>

						<div class="not-yet-open">
							<span class="not-yet-open-text">ただいま公開しておりません</span>
						</div>

						<div class="edit-open-garden">
							<%= link_to '公開情報の編集　>', new_open_garden_path(@post_garden.id), class:"btn btn-success" %>
						</div>

					<% elsif @user.id == current_user.id && @post_garden.open_status == "公開" %>

						<div class="open-now">
							<span class="open-now-text">ただいま公開中です</span>
						</div>

						<div class="edit-open-garden">
							<%= link_to '公開情報の編集　>', new_open_garden_path(@post_garden.id), class:"btn btn-success" %>
						</div>

					<% elsif @user.id != current_user.id && @post_garden.open_status == "非公開" %>

						<div class="not-yet-open">
							<span class="not-yet-open-text">ただいま公開しておりません</span>
						</div>


					<% elsif @user.id != current_user.id && @post_garden.open_status == "公開" %>

						<div id='calendar_reservation'></div>

						<!-- どの投稿のカレンダーか判別するため、idをjqueryに渡している -->
						<div class="params_num_show" data-params="<%= @post_garden.id %>"></div>

						<div class="to-reservation-page">
							<%= link_to '予約画面へ進む', new_reservation_path(@post_garden), class:"btn btn-primary" %>
						</div>

					<% end %>

				<!-- 非ログイン時の表示 -->
				<% else %>

					<% if @post_garden.open_status == "非公開" %>
						<div class="not-yet-open">
							<span class="not-yet-open-text">ただいま公開しておりません</span>
						</div>
					<% elsif @post_garden.open_status == "公開" %>
						<div id='calendar_reservation'></div>
						<!-- どの投稿のカレンダーか判別するため、idをjqueryに渡している -->
						<div class="params_num_show" data-params="<%= @post_garden.id %>"></div>
					<% end %>

				<% end %>

			</div>

		</div>

	</div>
</div>