config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins

  # ユーザ用ルーティング
  devise_for :users

  resources :users, only: %i[show edit update] do
    get 'users/following', to: 'users#following', on: :member
    get 'users/follower', to: 'users#follower', on: :member
    get 'likes', to: 'likes#index', on: :member
  end
  get 'users/:id/exit' => 'users#exit', as: 'exit'
  get 'users/:id/follower' => 'users#follower', as: 'follower'
  get 'users/:id/following' => 'users#following', as: 'following'

  resources :post_gardens, only: %i[new create show edit update destroy] do
    resources :post_comments, only: %i[create destroy]
    post 'likes', to: 'likes#create', on: :member
    delete 'likes', to: 'likes#destroy', on: :member
    post 'send_images', to: 'post_gardens#send_images', on: :collection
  end
  root to: 'post_gardens#index'
  get 'about' => 'post_gardens#about', as: 'about'
  get 'post_gardens/:id/new_open_garden' => 'post_gardens#new_open_garden', as: 'new_open_garden'
  get 'search_result' => 'post_gardens#search_result', as: 'search_result'
  patch 'post_gardens/:id/delete_open_info' => 'post_gardens#delete_open_info', as: 'delete_open_info'

  resources :post_images, only: [:destroy]

  resources :open_days, only: %i[create update destroy]
  # resources :new_open_garden

  resources :relationships, only: [:create]
  delete 'relationships/:id' => 'relationships#destroy', as: 'unfollow'

  resources :reservations, only: %i[create show edit update]
  get 'reservations/new/:id' => 'reservations#new', as: 'new_reservation'
  get 'done' => 'reservations#done', as: 'done'
  get 'accept_reservations/:id' => 'reservations#accept_reservations', as: 'accept_reservations'
  get 'request_reservations/:id' => 'reservations#request_reservations', as: 'request_reservations'
  get 'approve_reservation/:id' => 'reservations#approve_reservation', as: 'approve_reservation'
  get 'approved/:id' => 'reservations#approved', as: 'approved'
  get 'cancel_reason/:id' => 'reservations#cancel_reason', as: 'cancel_reason'
  get 'canceled/:id' => 'reservations#canceled', as: 'canceled'

  resources :notifications, only: :index

  resources :search_plants, only: %i[new show create]
end

app/views/layouts/_footer.html.erb
<footer>
	<div class="footer-box">
		<div class="logo-footer">
			<i class="fab fa-pagelines logo-leaf"></i>
		    <span class="logo-text"><b>Gardenia</b></span>
		</div>

		<p class="footer-text">Copyright© Gardenia, Inc. All Rights Reserved.</p>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header>
    <div class="container">
        <div class="row">

            <div class="logo col-xs-3">
                <%= link_to root_path, class:"logo-leaf" do %>
                    <i class="fab fa-pagelines"></i>
                    <span class="logo-text"><b>Gardenia</b></span>
                <% end %>
            </div>

            <div class="col-xs-3">
                <!-- 検索ボックス -->
                <%= search_form_for @search, url: search_result_path do |f| %>

                    <div class="input-group">
                        <span class="input-group-btn">
                            <%= f.button :type => "submit", class:"btn btn-default" do %>
                                <i class="fas fa-search"></i>
                            <% end %>
                        </span>

                        <%= f.search_field :post_content_or_place_or_problem_or_solution_or_tags_name_or_planted_gardens_plant_name_cont, class:"search_field", placeholder: '場所、庭木、キーワードで検索', class:"form-control search-box" %>
                    </div>
                <% end %>
            </div>

            <div class="col-xs-5 col-xs-offset-1 header-nav">

            <!-- 管理者でログインした場合 -->
                <% if admin_signed_in? %>
                    <div class="admin_user-box col-xs-6 col-xs-offset-6">
                        <span class="admin_user"> ショップ管理画面<br>　　　管理者　様</span>
                    </div>

                    <div class="admin-signout-box">
                        <%= link_to(destroy_admin_session_path, method: :delete) do %>
                            <span class="admin_signout"> サインアウト</span>
                        <% end %>
                    </div>


                <!-- ユーザでログインした場合 -->
                <% elsif user_signed_in?%>

                    <div class="header-top">
                            <% if unchecked_notifications.any? %>
                                <span class="header-menu">
                                    <span class="header-current_user"><u><%= current_user.user_name %>さん</u>
                                        <%= link_to notifications_path, class:"header-link" do %>
                                            <i class="fas fa-bell"></i>
                                        <% end %>
                                    </span>
                                </span>
                                <i class="fas fa-circle n-circle"></i>
                            <% else %>
                                <%= link_to notifications_path, class:"header-link" do %>
                                    <span class="header-menu">
                                        <span class="header-current_user"><u><%= current_user.user_name %>さん</u>
                                            <i class="fas fa-bell"></i>
                                        </span>
                                    </span>
                                <% end %>
                            <% end %>
                       

                    </div>

                    <span class="header-margin">
                        <%= link_to "Gardeniaとは？", about_path, class:"header-menu" %>
                    </span>

                    <span class="header-margin">
                        <%= link_to "マイページ", user_path(current_user.id), class:"header-menu" %>
                    </span>

                    <span class="header-margin">
                        <%= link_to "新規投稿", new_post_garden_path, class:"header-menu" %>
                    </span>

                    <span class="header-margin">
                        <%= link_to "サインアウト", destroy_user_session_path, method: :delete, class:"header-menu" %>
                    </span>


                    <!-- ログインしていない場合 -->
                <% else %>

                    <div class="before-login-header">
                        <span class="header-margin">
                            <%= link_to "Gardeniaとは？", about_path, class:"header-menu" %>
                        </span>

                        <span class="header-margin">
                            <%= link_to "新規登録", new_user_registration_path, class:"header-menu" %>
                        </span>

                        <span class="header-margin">
                            <%= link_to "ログイン", new_user_session_path, class:"header-menu" %>
                        </span>
                    </div>

                <% end %>
            </div>
        </div>
    </div>
</header>

app/views/layouts/_sidemenu.html.erb
<div class="col-xs-2">
	<div class="pickup-garden">
		<div class="side-title">
			<p class="pickup-garden-title"><strong>【新着】<br>公開中のお庭</strong><i class="fas fa-camera-retro icon-side"></i></p>
		</div>
	</div>
	<div class="popular-post-index">

		<% @open_gardens_side.each do |open_garden| %>
			<div class="mp-place-box-side">
					<span class="mp-place-side-text"><%= open_garden.open_prefecture %></span>
			</div>
			<div class="side-open-garden">
				<%= link_to post_garden_path(open_garden.id) do %>
					<%= attachment_image_tag open_garden.post_images[0], :garden_image, :fill, 120,120, format: 'jpg', class:"index-post-image" %>
				<% end %>
			</div>
		<% end %>
	</div>

	<div class="popular-tag-index">
		<div class="side-title">
			<p class="popular-tag-index-title"><strong>よく使うワード</strong><i class="fas fa-tag icon-side"></i></p>
		</div>
		<% @tags.each do |tag| %>
			<%= link_to search_result_path(tag_name: tag.name), class:"tag-label-link" do %>
				<span class="label tag-label"><%= tag %></span>
			<% end %>
		<% end %>
	</div>

	<div class="side-title">
		<p class="search-plant-title-text"><strong>この植物の名前は？</strong></p>
		<%= link_to "調べる >", new_search_plant_path, class:"btn btn-success" %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gardenia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- fontawesomeの読み込み -->
    <script src="https://kit.fontawesome.com/b1ddc8e955.js" crossorigin="anonymous"></script>

    <!-- bootstrap-tags-inputの読み込み(CSS) -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.css">

    <!-- ロゴのフォント取り込み -->
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap" rel="stylesheet">

    <!-- fullcalendarの読み込み(本来は必要だが、一度gemを読み込んだことで、どこかに記述されている)
    <link rel='stylesheet' href='/fullcalendar.css' />
    <script src='/lib/jquery.min.js'></script>
    <script src='/lib/moment.min.js'></script>
    <script src='/fullcalendar.js'></script>
    <script src='fullcalendar/locale/ja.js'></script>  -->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>

    <!-- bootstrap-tags-inputの読み込み（javascript) -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.min.js.map"></script>

  </body>
</html>